name: Build and Deploy Crowded Airport App

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install

      - name: Build the app
        run: npm run build

      - name: Start or Restart Crowded Airport App with PM2
        run: |
          if pm2 describe crowded-airport > /dev/null; then
            echo "Process crowded-airport found, restarting..."
            pm2 restart crowded-airport
          else
            echo "No process found, starting a new one..."
            pm2 start "npx next start" --name crowded-airport
          fi

      - name: Save PM2 process list
        run: pm2 save
