name: Deploy Crowded Airport App

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Add SSH key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SERVER_SSH_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan 5.78.112.252 >> ~/.ssh/known_hosts

      - name: Deploy via SSH
        uses: appleboy/ssh-action@master
        with:
          host: 5.78.112.252
          username: root
          key: ${{ secrets.SERVER_SSH_KEY }}
          script: |
            cd /var/www/crowded-airport
            git pull origin main

            if pm2 describe crowded-airport > /dev/null; then
              echo "Stopping all instances of crowded-airport..."
              pm2 delete crowded-airport
            fi

            # Install dependencies
            npm install

            # Build the app
            npm run build

            # Start the app using PM2
            pm2 start "npx next start" --name crowded-airport

      - name: Save PM2 process list
        uses: appleboy/ssh-action@master
        with:
          host: 5.78.112.252
          username: root
          key: ${{ secrets.SERVER_SSH_KEY }}
          script: pm2 save
